import GlobalState from "@/context";
// import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import Sidebar from "@/components/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "admin",
  description: "Generated by create next app",
};

export default function Admin({ children }) {
  return (
    <>
      <Sidebar></Sidebar>
      <div className="flex-2">{children}</div>
    </>
  );
}
