import GlobalState from "@/context";
import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Providers } from "./providers";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "shop clothes DHien",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="light">
      <body className={inter.className}>
        <Providers>
          <GlobalState>
            <Navbar />
            <main className="flex min-h-screen flex-col mt-[80px]">
              {children}
            </main>
            {/* <Footer></Footer> */}
            {/* <footer>sdfsdf</footer> */}
          </GlobalState>
        </Providers>
      </body>
    </html>
  );
}
